apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: b4mad-racing
resources:
  - influxdb.yaml 
  - grafana.yaml
  - grafana-route.yaml
  - kafka.yaml
  - kafka-topics.yaml
  - f1-telemetry-kafka-influxdb.yaml
  - f1-telemetry-streams-avg-speed.yaml